// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ypjmqcuxruwpoidmjkiw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlwam1xY3V4cnV3cG9pZG1qa2l3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjIzMTc4MjIsImV4cCI6MjA3Nzg5MzgyMn0._3N3xVoGjMxMWX5ERUDVad2mb3Fk4kKybwJHj4XTKfw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});